  ### GET All users:
GET http://localhost:8080/users
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlzQnVzaW5lc3MiOnRydWUsImlzQWRtaW4iOnRydWUsImlhdCI6MTcwNDU1MTk0OH0.I_AKWHioPcOsZTfUt_oJzynTtDARY8cUsEngEweYT9M


### Get user:
GET http://localhost:8080/users/6599661d036ae1da45e585c7
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlzQnVzaW5lc3MiOnRydWUsImlzQWRtaW4iOnRydWUsImlhdCI6MTcwNDU1MTk0OH0.I_AKWHioPcOsZTfUt_oJzynTtDARY8cUsEngEweYT9M



### Add a user:
POST http://localhost:8080/users
Content-Type: application/json


{
  "name": {
    "first": "Yaniv",
    "last": "Z"
  },
  "address": {
    "street": "123 Main St",
    "city": "Anytown",
    "country": "Israel",
    "houseNumber": 20,
    "zip": "12345"
  },
  "image": {
    "alt": "user-profile",
    "url": "https://picsum.photos/200/300"
  },
  "phone": "050-8123090",
  "email": "yz@walla.com",
  "isBusiness": false,
  "isAdmin": true,
  "password": "123456aA!" 
}


###Edit User
PUT  http://localhost:8080/users/65a2b21de2c2576355fcc271
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlzQnVzaW5lc3MiOnRydWUsImlzQWRtaW4iOnRydWUsImlhdCI6MTcwNDU1MTk0OH0.I_AKWHioPcOsZTfUt_oJzynTtDARY8cUsEngEweYT9M
Content-Type: application/json


{
  "name": {
    "first": "Bruce",
    "last": "Willis"
  },
  "address": {
    "street": "123 Main St",
    "city": "Anytown",
    "country": "Israel",
    "houseNumber": 20,
    "zip": "12345"
  },
  "image": {
    "alt": "user-profile",
    "url": "https://picsum.photos/200/300"
  },
  "phone": "050-8123090",
  "email": "Willis@batcave.com",
  "isBusiness": false,
  "password": "123456aA!" 
}

### Login:
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "email": "Willi@batcave.com",
  "password": "123456aA!"
}

### Login:
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "123456aA!"
}

###Edit User
PATCH http://localhost:8080/users/6575ba245a440e0ca0aefa7b
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlzQnVzaW5lc3MiOnRydWUsImlzQWRtaW4iOnRydWUsImlhdCI6MTcwNDU1NTYyN30.JVf5Ki7jWz0yLPi3Robw4tUECZpEuQjKBrIMicvb4Yw
Content-Type: application/json

{
  "isBusiness": true
}

//These are examples with users who will try to do things like delete or edit other users and more..

### get Wayne by id with JWT of Willis:
GET http://localhost:8080/users/65a560bbeacbcc903f7bb0e0
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IldpbGxpQGJhdGNhdmUuY29tIiwiaWQiOiI2NWE1NjI1ZGVhY2JjYzkwM2Y3YmIxMjAiLCJpc0J1c2luZXNzIjpmYWxzZSwiaXNBZG1pbiI6ZmFsc2UsImlhdCI6MTcwNTMzODk5NX0.IFqJJPuXzicWPsT_Jc3no9mfL62LN1J6E8-9yDvkGuc


### GET Willis by id with jwt of Willis
GET http://localhost:8080/users/65a560bbeacbcc903f7bb0e0
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IldpbGxpQGJhdGNhdmUuY29tIiwiaWQiOiI2NWE1NjI1ZGVhY2JjYzkwM2Y3YmIxMjAiLCJpc0J1c2luZXNzIjpmYWxzZSwiaXNBZG1pbiI6ZmFsc2UsImlhdCI6MTcwNTMzODk5NX0.IFqJJPuXzicWPsT_Jc3no9mfL62LN1J6E8-9yDvkGuc


### GET Wayne with JWT of admin:
GET http://localhost:8080/users/65a560bbeacbcc903f7bb0e0
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IldpbGxpQGJhdGNhdmUuY29tIiwiaWQiOiI2NWE1NjI1ZGVhY2JjYzkwM2Y3YmIxMjAiLCJpc0J1c2luZXNzIjpmYWxzZSwiaXNBZG1pbiI6ZmFsc2UsImlhdCI6MTcwNTMzODk5NX0.IFqJJPuXzicWPsT_Jc3no9mfL62LN1J6E8-9yDvkGuc


### PUT Bruce Wayne with JWT of Wayne:
PUT http://localhost:8080/users/65a560bbeacbcc903f7bb0e0
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IldpbGxpQGJhdGNhdmUuY29tIiwiaWQiOiI2NWE1NjI1ZGVhY2JjYzkwM2Y3YmIxMjAiLCJpc0J1c2luZXNzIjpmYWxzZSwiaXNBZG1pbiI6ZmFsc2UsImlhdCI6MTcwNTMzNzQ0NH0.k73FcpEBN1J8BajjHXLMPneRiV1b3X2S-vJfXB8kZy4
Content-Type: application/json

{
  "name": {
    "first": "Bruce!!!",
    "last": "Wayne!!!"
  },
  "address": {
    "street": "123 Main St",
    "city": "Anytown",
    "country": "Israel",
    "houseNumber": 20,
    "zip": "12345"
  },
  "image": {
    "alt": "user-profile",
    "url": "https://picsum.photos/200/300"
  },
  "phone": "050-8123091",
  "email": "Willis@batcave.com",
  "isBusiness": true,
  "password": "123456aA!" 
}

### DELETE Bruce Wayne with JWT of Wayne:
DELETE http://localhost:8080/users/65a560bbeacbcc903f7bb0e0
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IldpbGxpQGJhdGNhdmUuY29tIiwiaWQiOiI2NWE1NjI1ZGVhY2JjYzkwM2Y3YmIxMjAiLCJpc0J1c2luZXNzIjpmYWxzZSwiaXNBZG1pbiI6ZmFsc2UsImlhdCI6MTcwNTMzNzQ0NH0.k73FcpEBN1J8BajjHXLMPneRiV1b3X2S-vJfXB8kZy4
Content-Type: application/json
//--------------------------------------------------------------


### add a card: ### new card
POST http://localhost:8080/cards
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjoiNjU5YmZjMGY2M2IzZGJhMDBkYjI2ZTYxIiwiaXNCdXNpbmVzcyI6dHJ1ZSwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzA1MzQxMzA0fQ.TS7bFTMV5nKx_IJsYC5Vbym0eWbpM9klIYPPLAlPzvY
Content-Type: application/json

{
    "title": "Apple AirPods 3",
    "subtitle": "Apple AirPods 3",
    "description": "6.1-inch Super Retina XDR display footnote ¹ featuring ProMotion, Always-On, and Dynamic Island",
    "price": "100$",
    "shipping": "isreal",
    "image": {
        "url": "https://d3m9l0v76dty0.cloudfront.net/system/photos/4172344/large/3ec7e9ee00b01b5645f03a1fe166fd86.png",
        "alt": "Fintie"
    }
}


### Get all cards:
GET http://localhost:8080/cards

### Get my-cards:
GET http://localhost:8080/cards/my-cards
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTcwMjk3NDMxNH0.9rxSVJKljg9si33a7qNMz-5wunk0CfmW7tjDLAQr8nk


### GET Card by id:
GET http://localhost:8080/cards/65a50edae95149f380ab50d9

### Delete a Card
DELETE http://localhost:8080/cards/6599772e88a27ad9a5e21f33
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjoiNjU5YmZjMGY2M2IzZGJhMDBkYjI2ZTYxIiwiaXNCdXNpbmVzcyI6dHJ1ZSwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzA1MTU1ODQzfQ.PHJnLTQXYqC4nqT0CLQ-0egJOzlJS_WZLmshQ2RlqG8

### Request to Like a Card
PATCH http://localhost:8080/cards/65a5124c128978954177a3a1
Content-Type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjoiNjU5YmZjMGY2M2IzZGJhMDBkYjI2ZTYxIiwiaXNCdXNpbmVzcyI6dHJ1ZSwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzA1MTU1ODQzfQ.PHJnLTQXYqC4nqT0CLQ-0egJOzlJS_WZLmshQ2RlqG8

{
  "userId": "6599661d036ae1da45e585c7"
}


### Edit a Card
PUT http://localhost:8080/cards/65a57183101aee12dfa795d0
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjoiNjU5YmZjMGY2M2IzZGJhMDBkYjI2ZTYxIiwiaXNCdXNpbmVzcyI6dHJ1ZSwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzA1MzQxMzA0fQ.TS7bFTMV5nKx_IJsYC5Vbym0eWbpM9klIYPPLAlPzvY
Content-Type: application/json

{
  "title": "Updated Card Title",
  "subtitle": "Updated Subtitle",
  "description": "Updated card description",
  "phone": "050-9876543",
  "email": "admin@gmail.com",
  "web": "http://www.updatedwebsite.com",
  "address": {
    "city": "Updated City",
    "country": "Updated Country",
    "street": "Updated Street",
    "houseNumber": 22
  }
}


### Add to Cart
POST  http://localhost:8080/cards/65a5124c128978954177a3a1/add-to-cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjoiNjU5YmZjMGY2M2IzZGJhMDBkYjI2ZTYxIiwiaXNCdXNpbmVzcyI6dHJ1ZSwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNzA1MTU2NzE1fQ.dtHaDafuEZju6wl086JuR2-cRwqT8LAyldKtCR3FODY

